- name: variables from promt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: what is your username?
    private: false
  tasks:
  - name: Print cridentials
    ansible.builtin.debug:
     msg: "hello, username is : {{ username }} "