- name: working on variables
  hosts: local
  connection: local

  vars:
   COURSE: Ansible
   DURATION: 120hrs
   TRAINER: Anurag

  tasks:
  # - name: printing the cource info
  #   vars:
  #     COURSE: "Ansible With RHEL"
  - debug:
      msg: "Cource is: {{ COURSE }} Duration is:{{ DURATION }}, and the Trainer is: {{ TRAINER }}"

  - name: printing cource info at Task level-2 
    vars:
      COURSE: "DevOps With Aws"
      DURATION: 200hrs
      TRAINER: Keerthi
    debug:
      msg: "Cource is: {{ COURSE }} Duration is:{{ DURATION }}, and the Trainer is: {{ TRAINER }} this is level 2"

  