- name: functions
  hosts: local
  connection: local
  vars:
    tech: DevOps, Linux, Shell, Ansible
    tags:
      cloud: AWS
      Laungage: Shell
      Tool: Ansible
  tasks:
  - name: implementing functions
    debug:
      msg: "hello {{name | default('Anurag')}}" 
  - name: convert string to list
    debug:
      msg: "Techonologys are {{tech | split(',')}}"
  - name: Dict to list
    debug:
      msg: "list are {{tags | dict2items}}"