- name: functions
  hosts: local
  connection: local
  vars:
    tech: DevOps, Linux, Shell, Ansible
    name: "anurag bojja"
    tags:
      cloud: AWS
      Laungage: Shell
      Tool: Ansible
    listTags:
    - key: Application
      value: RoboShop
    - key: Env
      value: dev
  tasks:
  - name: implementing functions
    debug:
      msg: "hello {{name | default('Anurag')}}" 
  - name: convert string to list
    debug:
      msg: "Techonologys are {{tech | split(',')}}"
  - name: Dict to list
    debug:
      msg: "list are {{tags | dict2items}}"

  - name: list to dicr
    debug:
      msg: "tags maps: {{listTags | items2dict}}"

  - name: Read yaml 
    set_fact:
      student_yaml: "{{ lookup('file','student.yaml') | from_yaml }}"

  - name: convert yaml into json
    debug:
      msg: "JSON : {{student_yaml | to_json}}"
  
  - name: Save JSON file 
    copy:
      dest: ./student-data.json
      content: "{{ student_yaml | to_nice_json }}"
  
  - name: name correct
    debug:
      msg: 
       - "{{name}}"
       - "{{name | title}}"
       - "Done"
    
  - name: grep for root
    shell: cat /etc/passwd | grep root
    register: command_output
  
  - name: print command command_output
    debug:
      msg: "{{command_output}}"
  
  - name: list of files command
    command: ls -ltr
    register: list_output
  
  - name: print list_output
    debug:
      msg: "{{list_output}}"